-- =========================================================
-- IRIS BOTANICA AI
-- PostgreSQL Database
-- =========================================================

-- 1. NGƯỜI DÙNG
CREATE TABLE IF NOT EXISTS nguoi_dung (
    ma_nguoi_dung INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ten_dang_nhap VARCHAR(50) NOT NULL UNIQUE,
    mat_khau VARCHAR(255) NOT NULL,
    ngay_tao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    trang_thai BOOLEAN NOT NULL DEFAULT TRUE
);

-- 2. LỊCH SỬ ĐĂNG NHẬP
CREATE TABLE IF NOT EXISTS lich_su_dang_nhap (
    ma_dang_nhap INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_nguoi_dung INT NOT NULL,
    thoi_gian_dang_nhap TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_lich_su_dang_nhap_nguoi_dung
        FOREIGN KEY (ma_nguoi_dung)
        REFERENCES nguoi_dung(ma_nguoi_dung)
);

-- 3. LỊCH SỬ DỰ ĐOÁN
CREATE TABLE IF NOT EXISTS lich_su_du_doan (
    ma_du_doan INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_nguoi_dung INT NOT NULL,
    sepal_length DOUBLE PRECISION NOT NULL,
    sepal_width DOUBLE PRECISION NOT NULL,
    petal_length DOUBLE PRECISION NOT NULL,
    petal_width DOUBLE PRECISION NOT NULL,
    ket_qua INT NOT NULL,
    ten_mo_hinh VARCHAR(20) NOT NULL,
    thoi_gian_chay DOUBLE PRECISION NOT NULL,
    thoi_gian_du_doan TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    da_xoa BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT FK_lich_su_du_doan_nguoi_dung
        FOREIGN KEY (ma_nguoi_dung)
        REFERENCES nguoi_dung(ma_nguoi_dung)
);

-- 4. MÔ HÌNH
CREATE TABLE IF NOT EXISTS mo_hinh (
    ma_mo_hinh INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ten_mo_hinh VARCHAR(50) NOT NULL UNIQUE,
    loai_mo_hinh VARCHAR(50),
    mo_ta VARCHAR(255),
    trang_thai BOOLEAN NOT NULL DEFAULT TRUE
);

-- 5. KẾT QUẢ MÔ HÌNH
CREATE TABLE IF NOT EXISTS ket_qua_mo_hinh (
    ma_ket_qua INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_mo_hinh INT NOT NULL,
    accuracy DOUBLE PRECISION NOT NULL,
    precision DOUBLE PRECISION NOT NULL,
    recall DOUBLE PRECISION NOT NULL,
    f1_score DOUBLE PRECISION NOT NULL,
    thoi_gian_huan_luyen DOUBLE PRECISION,
    thoi_gian_du_doan DOUBLE PRECISION,
    CONSTRAINT FK_ket_qua_mo_hinh_mo_hinh
        FOREIGN KEY (ma_mo_hinh)
        REFERENCES mo_hinh(ma_mo_hinh)
);

-- 6. LỊCH SỬ MÔ HÌNH
CREATE TABLE IF NOT EXISTS lich_su_mo_hinh (
    ma_lich_su INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ma_mo_hinh INT NOT NULL,
    accuracy DOUBLE PRECISION NOT NULL,
    precision DOUBLE PRECISION NOT NULL,
    recall DOUBLE PRECISION NOT NULL,
    f1_score DOUBLE PRECISION NOT NULL,
    thoi_gian_huan_luyen DOUBLE PRECISION,
    thoi_gian_du_doan DOUBLE PRECISION,
    thoi_gian_chay TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_lich_su_mo_hinh_mo_hinh
        FOREIGN KEY (ma_mo_hinh)
        REFERENCES mo_hinh(ma_mo_hinh)
);

-- 7. DỮ LIỆU MÔ HÌNH
INSERT INTO mo_hinh (
    ten_mo_hinh,
    loai_mo_hinh,
    mo_ta,
    trang_thai
)
VALUES
(
    'SVM',
    'Supervised Learning',
    'Phan loai hoa Iris bang Support Vector Machine voi kernel tuyen tinh.',
    TRUE
),
(
    'LDA',
    'Supervised Learning',
    'Phan loai hoa Iris bang Linear Discriminant Analysis.',
    TRUE
),
(
    'KNN',
    'Supervised Learning',
    'Phan loai hoa Iris bang K-Nearest Neighbors.',
    TRUE
);

-- 8. KẾT QUẢ ĐÁNH GIÁ MÔ HÌNH
INSERT INTO ket_qua_mo_hinh (
    ma_mo_hinh,
    accuracy,
    precision,
    recall,
    f1_score,
    thoi_gian_huan_luyen,
    thoi_gian_du_doan
)
VALUES
(1, 1.0000, 1.0000, 1.0000, 1.0000, 0.008273, 0.002062),
(2, 1.0000, 1.0000, 1.0000, 1.0000, 0.017877, 0.000727),
(3, 0.9667, 0.9697, 0.9667, 0.9666, 0.005230, 0.009872);